# Volume Snapshot Class for DigitalOcean Block Storage
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotClass
metadata:
  name: do-block-storage-snapshot
  annotations:
    snapshot.storage.kubernetes.io/is-default-class: "true"
driver: dobs.csi.digitalocean.com
deletionPolicy: Delete 